name: testlogic
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.0.0
  dart_format: ^1.1.20
  another_flushbar: ^1.12.30
  super_tooltip: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/BackGround/Empty.png
    - assets/Icon/Frame 12255.png
    - assets/Icon/Home Indicator.png
    - assets/BackGround/Th√¥ng tin 1.png
    - assets/Icon/Frame 12255 (1).png
    - assets/BackGround/camera.png
    - assets/Icon/Frame 12255 (2).png
    - assets/Icon/error.png
    - assets/Icon/info.png
    - assets/Icon/success.png
    - assets/Icon/warning.png
    - assets/Icon/bgElements.png
    - assets/Icon/ErrorIcon.png
    - assets/Icon/Icon2.png
    - assets/Icon/Icon3.png
    - assets/Icon/Icon4.png
    - assets/Icon/Icon5.png
    - assets/Icon/Icon6.png
